FORMAT: 1A
HOST: http://theaustinites.pythonanywhere.com/api

# Austin City Limits Project API
ACL API is a representation of the bands, stages, events, and artists appearing at 
**Austin City Limits**.

# Group Stage

## Stage [/stages/{id}]
A single stage object. The Stage resource represents a stage.

The Stage resource has the following attributes:

- id
- name

The stages *id* are assigned by the ACL Project API at the moment of creation.

+ Parameters
    + id (integer) ... ID of the Stage in the form of a number
    
+ Model (application/hal+json)
    HAL+JSON representation of Stage resource.

    + Headers
    
            Link: <https://theaustinites.pythonanywhere.com/stages/42>;rel="self"
        
    + Body
    
            {
                "_links": {
                    "self": { "href": "stages/42" }
                },
                "id": "42",
                "name": "Stage name"
            }

### Retrieve a single Stage [GET]
+ Response 200 (application/json)

        [Stage][]
        
### Edit a stage [PATCH]
To update a Stage send a JSON with the update value(s)

+ Request (application/json)

        {
            "name": "Updated file contents"
        }

+ Response 200

    [Stage][]

### Delete a Stage [DELETE]
+ Response 204


## Stage Collection [/Stages]
Collection of all Stages

It **embeds** *Stage Resources* in the ACL Project API

+ Model (application/hal+json)

        HAL+JSON representation of the Stage Collection Resource.  The Stage resources in the collections are embedded.

        + Headers
            
            Link: <https://theaustinites.pythonanywhere.com/stages>;rel="self"
            
        + Body
            
            {
                "_links": {
                    "self": { "href": "/stages" }
                },
                "_embedded": {
                    "stages": [
                        {
                            "_links" : {
                                "self": { "href": "stages/42" }
                            },
                            "id": "42",
                            "name": "Stage name"
                        }
                    ]
                }
            }
            
### List All Stages [GET]
+ Response 200
    
    [Stage Collection][]

### Create a Stage [POST]
To create a stage provide the JSON hash of the *name* attribute

+ Request (application/json)
        
        {
            "name": "Name of stage"
        }

+ Response 201 (application/hal+json)

    [Stage][]
    
# Group Sponsor
Sponsor related resources of the **ACL API**

## Sponsor [/sponsors/{id}]
A single sponsor object.  The Sponsor resource represents a sponsor

The Sponsor resource has the following attributes:

- id
- name
- business_type
- website
- stage

The state *id* are assigned by the ACL Project API at the moment of creation.

+ Parameters
    + id (integer) ... ID of the Sponsor in the form of a number
    
+ Model (application/hal+json)
    HAL+JSON representation of Sponsor resource.

    + Headers
    
            Link: <https://theaustinites.pythonanywhere.com/sponsor/42>;rel="self"
        
    + Body
    
            {
                "_links": {
                    "self": { "href": "sponsors/42" }
                },
                "id": "42",
                "name": "Sponsor name",
                "business_type": "Type of Business",
                "website": "URL of sponsor website",
                "stage": "Stage id"
            }

### Retrieve a single Sponsor [GET]
+ Response 200 (application/json)

        [Sponsor][]
        
### Edit a Sponsor [PATCH]
To update a Sponsor send a JSON with the update value(s)

+ Request (application/json)

        {
            "name": "Updated name",
            "business_type": "Updated business type",
            "website": "Updated URL",
            "stage": "Updated stage id"
        }

+ Response 200

    [Sponsor][]

### Delete a Sponsor [DELETE]
+ Response 204


## Sponsor Collection [/sponsors]
Collection of all Sponsors

It **embeds** *Sponsor Resources* in the ACL Project API

+ Model (application/hal+json)

        HAL+JSON representation of the Sponsor Collection Resource.  The Sponsor resources in the collections are embedded.

        + Headers
            
            Link: <https://theaustinites.pythonanywhere.com/sponsors>;rel="self"
            
        + Body
            
            {
                "_links": {
                    "self": { "href": "/sponsors" }
                },
                "_embedded": {
                    "stages": [
                        {
                            "_links" : {
                                "self": { "href": "sponsor/42" }
                            },
                            "id": "42",
                            "name": "Sponsor name",
                            "business_type": "Type of Buisiness",
                            "website": "URL of sponsor"
                            "stage": "Stage ID"
                        }
                    ]
                }
            }
            
### List All Sponsors [GET]
+ Response 200
    
    [Sponsor Collection][]

### Create a Sponsor [POST]
To create a sponsor provide the JSON hash of the *name*, *buisiness_type*, *website*, and *stage* attributes

+ Request (application/json)
        
        {
            "name": "Name of stage",
            "business_type": "Type of Buisiness",
            "website": "URL of sponsor"
            "stage": "Stage ID"
        }

+ Response 201 (application/hal+json)

    [Sponsor][]
    
# Group Artist
Artist related resources of the **ACL API**

## Artist [/artists/name]
A single Artist object with all its details

The Artist resource has the following attributes:

- id
- name
- label
- origin
- website
- genre
- stage

The artist **ids** are assigned by the ACL Project API at the moment of creation.
+ Parameters

    + name (required, string, `Outkast`) ... `name` of the Artist to perform action with.
    
    
+ Model (application/hal+json)
    HAL+JSON representation of Artist resource.

    + Headers
    
            Link: <https://theaustinites.pythonanywhere.com/artists/Outkast>;rel="self"
        
    + Body
    
            {
                "_links": {
                    "self": { "href": "artists/Outkast" }
                },
                "id": "42",
                "name": "Artist name"
                "label": "Label of artist"
                "origin": "Where the artist was from"
                "website": "URL to the artist"
                "genre": "Genre of the artist"
                "stage": "Stage the artist performs in"
            }
            
### Modify an Artist [PUT]
+ Request (application/json)
        
        {
            "name": "Name of artist"
            "label": "Label of artist"
            "origin": "Where the artist was from"
            "website": "URL to the artist"
            "genre": "Genre of the artist"
            "stage": "Stage the artist performs in"
        }

+ Response 201 (application/hal+json)

    

### Retrieve an Artist [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "name": "Name of artist"
                "label": "Label of artist"
                "origin": "Where the artist was from"
                "website": "URL to the artist"
                "genre": "Genre of the artist"
                "stage": "Stage the artist performs in"
            }
            

### Remove an Artist [DELETE]
+ Response 204

## Artist Collection [/artists]
Collection of all Artists

+ Model (application/hal+json)

        HAL+JSON representation of the Artist Collection Resource.  

        + Headers
            
            Link: <https://theaustinites.pythonanywhere.com/artists>;rel="self"
            
        + Body
            
            {
                "_links": {
                    "self": { "href": "/artists" }
                },
                "_embedded": {
                    "artists": [
                        {
                            "_links" : {
                                "self": { "href": "artists/" }
                            },
                                "name": "Name of artist"
                                "label": "Label of artist"
                                "origin": "Where the artist was from"
                                "website": "URL to the artist"
                                "genre": "Genre of the artist"
                                "stage": "Stage the artist performs in"
            
                        }
                    ]
                }
            }
            
### List All Artists[GET]
+ Response 200
    
    [Sponsor Collection][]

### Create an Artist [POST]

+ Request (application/json)
        
        {
            "name": "Name of artist"
            "label": "Label of artist"
            "origin": "Where the artist was from"
            "website": "URL to the artist"
            "genre": "Genre of the artist"
            "stage": "Stage the artist performs in"
        }

+ Response 201 (application/hal+json)

    [Artist][]




