FORMAT: 1A
HOST: http://theaustinites.pythonanywhere.com/

# Austin City Limits Project API
ACL Project is a representation of the bands, stages, events, and artists appearing at 
**Austin City Limits**.

The API allows **GET** requests to the following:

* Stages
* Sponsors
* Artists
* ArtistMedia
* StageMedia
* SponsorMedia

**Note:** The ACL API allows information to be selected on a per year basis. 
The earliest available year starts at 2012.

# Group Stage
Stage related resources of the Austin City Limits Project API

## Stage [/api/stages/{location}/]
A single stage object.   

The Stage resource has the following attributes:

- location

The stage's *location* is assigned by the ACL Project API at the moment of creation.
The Stage resource represents a physical location on the Austin City Limits map.
see http://theaustinites.pythonanywhere.com/stages/.
Note that depending on the year of the festival, a stage may have a different
sponsor sponsoring that stage or different artists playing on that stage.

+ Parameters
    + location (integer) ...  a number
    
+ Model (application/json)
    JSON representation of Stage resource.

    + Body
    
            {
                "years": [2011,2012,2013,2014]
            }

### Retrieve a single Stage [GET]
A GET request returns a json dictionary with a key "year"
and the years that that particular stage location has been in use for the 
festival.

+ Response 200 (application/json)

    [Stage][]
        
## Stage Collection [/api/stages/{location}/{year}]
A stage collection returns information about it's *sponsor*
and *artists* that play on that stage for the given year. 

+ Model (application/json)

        JSON representation of the Stage Collection Resource.  The Stage resources in the collections are embedded.

        + Body
            
            [
                {   "location": 1
                    "sponsor": 'Honda',
                    "artists": ['Kendrick Lamar','Skrilex',...]
                }
            ]

### List Stage Information for a given year [GET]
A GET request for a **Stage Collection** returns the *location*, *sponsor* for 
the requested stage location and year as well as a *list of artists*
that have played on that stage during the requested year.
+ Response 200
    
    [Stage Collection][]
    
# Group Sponsor
Sponsor related resources of the **ACL API**

## Sponsor [/api/sponsors/{id}/]
A single sponsor object.

The Sponsor resource has the following attributes:
- id
- name
- industry

+ Parameters
    + id (integer) ... ID of the Sponsor in the form of a number
    
+ Model (application/json)
    JSON representation of Sponsor resource.

    + Body
    
            {
                "id": 42,
                "name": "Tito's Handmade Vodka",
                "industry": "alcohol industry"
            }

### Retrieve a single Sponsor [GET]
A GET request for a sponsor with given id returns 
the *id*, *name*, and *industry* the sponsor is associated with.
Note that sponsor names are unique.
+ Response 200 (application/json)

    [Sponsor][]


## Sponsor Collection [/api/sponsors/year/{year}]
Collection of all Sponsors that sponsored a Stage for the requested year.
+ Model (application/json)

        JSON representation of the Sponsor Collection Resource.  
        The Sponsor resources in the collections are embedded.

        + Body
            
            [
                {
                    "sponsors": ['id of sponsor 1','id of sponsor 2', etc...]
            
                }
            ]

            
### List All Sponsors for a given year[GET]
A GET request returns a json dictionary with a sponsors key and a list
of ids corresponding to a sponsor.

+ Response 200
    
    [Sponsor Collection][]

    
# Group Artist
Artist related resources of the **ACL API**

## Artist [/api/artists/{id}/]
A single Artist object with all its details

The Artist resource has the following attributes:

- id
- name
- label
- origin
- genre

The artist **id** is assigned by the ACL Project API at the moment of creation.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Artist to perform action with.

    
+ Model (application/json)
    JSON representation of Artist resource.

    + Body
    
            [   
                {
            
                "id": 42,
                "name": "Artist name"
                "label": "Label of artist"
                "origin": "Where the artist was from"
                "genre": "Genre of the artist"
                
                }
            ]   


### Retrieve an Artist [GET]
+ Response 200 (application/json)

    [Artist][]
    

## Artist Collection [/api/artists/year/{year}]
Collection of all Artists for a given year

It **embeds** *Artist Resources* in the ACL Project API

+ Model (application/json)

        JSON representation of the Sponsor Collection Resource.  The Sponsor resources in the collections are embedded.

        + Body
            [
                {
                    "artists": [id of artist,...]
                    
                }
            ]

            
### List All Artists [GET]
A GET request returns a json dictionary with an artists key whose value
is a list of artist id's.
+ Response 200
    
    [Artist Collection][]

# Group Media
Media related resources for Artist, Stage, and Sponsor

## ArtistMedia [/api/artists/{id}/media/]
A single ArtistMedia object with all its details

The ArtistMedia resource has the following attributes:

- ar (the artist)
- bio
- photo
- youtube
- video
- twitter
- facebook
- twitterwidget
- youtubevideo
- webpage

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the ArtistMedia to perform action with.

    
+ Model (application/json)
    JSON representation of ArtistMedia resource.

    + Body
    
            {
             "ar" : 42
             "bio" : "a description"
             "photo" : "url"
             "youtube"  "url"
             "video" : "url"
             "twitter" : "url"
             "facebook" : "url"
             "twitterwidget" : "twitter handle"
             "webpage" : "url"
            }
            
### Retrieve an ArtistMedia [GET]
+ Response 200 (application/json)

    [ArtistMedia][]

## SponsorMedia [/api/sponsors/{id}/media/]
A single SponsorMedia object with all its details

The SponsorMedia resource has the following attributes:

- sp (the sponsor)
- bio
- photo
- youtube
- video
- twitter
- facebook
- twitterwidget
- youtubevideo
- webpage

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the SponsorMedia to perform action with.

    
+ Model (application/json)
    JSON representation of ArtistMedia resource.

    + Body
    
            {
             "sp" : 42
             "bio" : "a description"
             "photo" : "url"
             "youtube"  "url"
             "video" : "url"
             "twitter" : "url"
             "facebook" : "url"
             "twitterwidget" : "twitter handle"
             "webpage" : "url"
            }
            
### Retrieve an SponsorMedia [GET]
+ Response 200 (application/json)

    [SponsorMedia][]
    
## StageMedia [/api/stages/{id}/media/]
A single StageMedia object with all its details

The StageMedia resource has the following attributes:

- st (the stage)
- bio
- photo
- youtube
- video
- twitter
- facebook
- twitterwidget
- youtubevideo
- webpage

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the StageMedia to perform action with.

    
+ Model (application/json)
    JSON representation of StageMedia resource.

    + Body
    
            {
             "st" : 42
             "bio" : "a description"
             "photo" : "url"
             "youtube"  "url"
             "video" : "url"
             "twitter" : "url"
             "facebook" : "url"
             "twitterwidget" : "twitter handle"
             "webpage" : "url"
            }
            
### Retrieve an StageMedia [GET]
+ Response 200 (application/json)

    [StageMedia][]
